### ISSUE TITLE
✨ New component requests

### ISSUE THREAD

**Issue by jd-solanki** [jd-solanki/anu#171]
Hi 👋🏻 

We will use this issue to track new component requests.

## How to request for new component

Just comment on this issue 😇 

I will add a requested component to the list.

## How component will get prioritized

We will prioritize components requested by the sponsor of the project and other feature requests will fall in order based on the requested time.

> **Note**
> We may re-order component implementation order based on how many upvotes (thumbs up) we get for that component.

## 👨🏻‍💻  Component Implementation order

- [ ] Slider (requested by our sponsor @husayt, Originally requested by @jsmnbom in #160)
- [ ] Notification/Toast/Snackbar (requested by our sponsor @husayt in discussion #116)
- [ ] Button group (#127)
- [ ] Pagination (#122)
- [ ] AutoComplete (requested by our sponsor @husayt in discussion #110)
- [ ] Timeline (#126)
- [ ] Button sheet (#30 - We can use Drawer ATM)

**Comment by jd-solanki** [comment]
Slider component

> _Thumbs up for upvote_

**Comment by jd-solanki** [comment]
Button group component

> _Thumbs up for upvote_

**Comment by jd-solanki** [comment]
Pagination component

> _Thumbs up for upvote_

**Comment by jd-solanki** [comment]
Timeline component

> _Thumbs up for upvote_

**Comment by jd-solanki** [comment]
Bottom sheet component

> _Thumbs up for upvote_

**Comment by jd-solanki** [comment]
I'm closing this issue because it will be unclear if someone has to comment on a specific component's feature request like [this](https://github.com/jd-solanki/anu/issues/139#issuecomment-1460192339). We will track component order in Anu project board.

However, Fist message of this issue is still valid.

Thanks.
